---
title: "Signal Correlations"
author: "DC King - Onish lab"
date: "5/19/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message=FALSE)
library(tidyr)
library(dplyr)
library(GenomicRanges)
library(magrittr)
library(knitr) # for kable
library(ggplot2)
library(cowplot)
library(multcompView)
library(ggridges)
library(ggpubr)
library(dunn.test)
library(ggpmisc)
library(rms)
#install.packages('contrast') 
library('contrast')
source('david-reader.R')
source('signal_cor_functions.R')
okabe <- c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
```

## ELT-2 data

```{r read-data-ELT-2}
elt2.data = read_ELT2_binding_data(as_genomic_ranges = FALSE)
#glimpse(elt2.data)
```

## Rob data

```{r read-rob-merged}
rob = read_rob_all_merged() %>% dplyr::select(-starts_with("pvalue."),-starts_with("lfcSE."))
glimpse(rob)
```

```{r combine-elt-2-rnaseq}
merge = right_join(rob, elt2.data, by = "WBGeneID")
# glimpse(merge)

# Left-over genes are NA in alldata. Give them a label
merge$embryo_int_exp[is.na(merge$embryo_int_exp)] = 'ftr'
merge$L1_int_exp[is.na(merge$L1_int_exp)] = 'ftr'
merge$L3_int_exp[is.na(merge$L3_int_exp)] = 'ftr'

merge$embryo.boundEnrichedStatus = sprintf("%s.%s", ifelse(merge$LE_bound, "bound", "unbound"), merge$embryo_int_exp)
merge$L1.boundEnrichedStatus = sprintf("%s.%s", ifelse(merge$L1_bound, "bound", "unbound"), merge$L1_int_exp)
merge$L3.boundEnrichedStatus = sprintf("%s.%s", ifelse(merge$L3_bound, "bound", "unbound"), merge$L3_int_exp)

# fix a name 
merge %<>% dplyr::rename(L3.log_chip_signal_mean = L3_log.chip_signal_mean)
```

```{r log2-chip-to-log10, eval=FALSE}
merge %<>% dplyr::mutate(LE.log_chip_signal_mean = LE.log_chip_signal_mean*log(2,10),
                  LE.log_chip_signal_max  = LE.log_chip_signal_max*log(2,10),
                  L1.log_chip_signal_mean = L1.log_chip_signal_mean*log(2,10),
                  L1.log_chip_signal_max  = L1.log_chip_signal_max*log(2,10),
                  L3.log_chip_signal_mean = L3.log_chip_signal_mean*log(2,10),
                  L3.log_chip_signal_max  = L3.log_chip_signal_max*log(2,10)
                  )
```

```{r choose-columns}

alldata = merge %>% dplyr::select(ends_with("log_chip_signal_mean"), 
                        starts_with("rlogc."),
                        starts_with("log2FoldChange."),
                        ends_with(".boundEnrichedStatus"),
                        ends_with("_int_exp"),
                        ends_with("_bound"),
                        din.status.description,
                        wikigene_name,
                        WBGeneID)

alldata$embryo_int_exp %<>% factor(levels=c("equal","depleted","enriched","ftr"))
alldata$L1_int_exp %<>% factor(levels=c("equal","depleted","enriched","ftr"))
alldata$L3_int_exp %<>% factor(levels=c("equal","depleted","enriched","ftr"))
```

# Linear models

## Embryo

```{r embryo-r-squared}
#data = alldata %>% filter(embryo_int_exp %in% c('enriched','equal'))
data = alldata %>% filter(embryo_int_exp %in% c('enriched'))
#data %<>% filter(WBGeneID != 'WBGene00016153') # negative signal, lowest point
#data %<>% filter(WBGeneID != 'WBGene00012762') # kind of hot region, highest point in "depleted"

# trim extreme .1%
q.LE.chipsig = quantile(data$LE.log_chip_signal_mean, c(1-.9995,.9995))
q.rlogc.embryo = quantile(data$rlogc.embryo, c(1-.9995,.9995),na.rm=T)
data %<>% filter(between(LE.log_chip_signal_mean, q.LE.chipsig[1],q.LE.chipsig[2]))
data %<>% filter(between(rlogc.embryo, q.rlogc.embryo[1],q.rlogc.embryo[2]))

# base model (0): chip signal
mod.embryo0 = lm.combo(rlogc.embryo ~ LE.log_chip_signal_mean, 
                       data = data)

mod.embryo0$label = "ChIP signal only"
mod.embryo1 = lm.combo(rlogc.embryo ~ LE.log_chip_signal_mean * LE_bound, 
                       data = data)

.mod.embryo1 = lm(rlogc.embryo ~ LE.log_chip_signal_mean * LE_bound, 
                       data = data)

embryo_contrast_bound_unbound = contrast(.mod.embryo1, list(LE_bound=FALSE,
                    LE.log_chip_signal_mean=mean(data$LE.log_chip_signal_mean)),
         list(LE_bound=TRUE,
              LE.log_chip_signal_mean=mean(data$LE.log_chip_signal_mean))
         )

mod.embryo1$label = "ChIP signal AND ELT-2 binding"


LE.straightup.cor = cor(data$LE.log_chip_signal_mean, data$rlogc.embryo)
dbound = data %>% filter(LE_bound)
dunbound = data %>% filter(!LE_bound)
LE.bound.cor = cor.test(dbound$LE.log_chip_signal_mean, dbound$rlogc.embryo, conf.level=.975)
LE.unbound.cor = cor.test(dunbound$LE.log_chip_signal_mean, dunbound$rlogc.embryo, conf.level=.975)

data %<>% mutate(elt2.binding = factor(ifelse(LE_bound, "ELT-2 bound", "ELT-2 unbound"),
                                       levels = c("ELT-2 unbound","ELT-2 bound")))

p1=ggplot(data, 
       aes(x=LE.log_chip_signal_mean, 
           y=rlogc.embryo, 
           #group=elt2.binding, 
           color=elt2.binding)) + 
  geom_point(alpha=.5) +
  geom_smooth(color="black", method="lm", formula = y~x, se=F) + 
  #stat_poly_eq(parse=T, aes(label = ..rr.label..), formula=y~x) +
  ggtitle(bquote(.(mod.embryo0$label) ~ R^2 == .(round(mod.embryo0$r.squared,3)))) +
  ylab("DESeq2 rlog counts") +
  xlab("LE log ChIP promoter signal") +
  scale_color_manual(values=okabe) #+ 
  #guides(color="none")

p2=ggplot(data,
       aes(x= LE.log_chip_signal_mean, 
           y=rlogc.embryo, 
           #group=elt2.binding, 
           color=elt2.binding
           )) + geom_point() +
  stat_smooth(color="black", method="lm", formula = y~x, se=F) + 
  stat_poly_eq(parse=T, aes(label = ..rr.label..), formula=y~x, color="black") +
  ylim(c(0,19)) + 
  #xlim(c(0,11)) +
  facet_wrap(~elt2.binding ) +
  ylab("DESeq2 rlog counts") + 
  xlab("LE log ChIP promoter signal") +
  ggtitle("Embryo Expression level (ELT-2 bound/unbound)") +
  scale_color_manual(values=okabe) + 
  guides(color="none") + theme_bw()

p3=ggplot(data %>% filter(!is.na(din.status.description)),
       aes(x= LE.log_chip_signal_mean, 
           y=rlogc.embryo, 
           #group=elt2.binding, 
           color=elt2.binding
           )) + geom_point() +
  stat_smooth(method="lm", formula = y~x, se=F) + 
  stat_poly_eq(parse=T, aes(label = ..rr.label..), formula=y~x) +
  ylim(c(0,19)) + 
  #xlim(c(0,11)) +
  facet_wrap(~din.status.description ) +
  ylab("DESeq2 rlog counts") + 
  xlab("LE log ChIP promoter signal") +
  ggtitle("Embryo Expression level (ELT-2 bound/unbound)") +
  scale_color_manual(values=okabe) + 
  guides(color="none"); p3


title <- ggdraw() + 
  draw_label(
    "Embryo: Intestine enriched and equal expressed genes predicted by ChIP signal level",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    # add margin on the left of the drawing canvas,
    # so title is aligned with left edge of first plot
    plot.margin = margin(0, 0, 0, 7)
  )
# plot_grid(title, p1, p2, p3, ncol=1,labels=c('','A','B','C'), rel_heights = c(0.1, 1, 1, 1)); 
#ggsave("plots/signal_cor.xy.embryo.pdf", height=15,width=12)

# middle one only (bound vs. unbound)
plot_grid(title, p2, ncol=1,rel_heights = c(0.1,1)); 
ggsave("plots/signal_cor.xy.embryo.pdf", height=5,width=12)

LE.p.title = title
LE.p1 = p1
```

```{r get-embryo-set}
data = alldata %>% dplyr::filter(embryo_int_exp %in% c('enriched') & LE_bound &  din.status.description %in% c("down_ELT2_minus", "up_ELT2_minus")) %>% select(WBGeneID, LE.log_chip_signal_mean, rlogc.embryo, din.status.description, embryo_int_exp, LE_bound, wikigene_name)

# trim extreme .1%
# q.LE.chipsig = quantile(data$LE.log_chip_signal_mean, c(1-.9995,.9995))
# q.rlogc.embryo = quantile(data$rlogc.embryo, c(1-.9995,.9995),na.rm=T)
# data %<>% filter(between(LE.log_chip_signal_mean, q.LE.chipsig[1],q.LE.chipsig[2]))
# data %<>% filter(between(rlogc.embryo, q.rlogc.embryo[1],q.rlogc.embryo[2]))

nrow(data)
head(data)
write.table(data, file="embryo_bound_elt2_minus_changed.tsv", sep="\t", row.names = F, quote = F)
```

## L1

```{r L1-r-squared}
data = alldata %>% filter(L1_int_exp %in% c('enriched'))
#data %<>% filter(WBGeneID != 'WBGene00016153') # negative signal, lowest point
#data %<>% filter(WBGeneID != 'WBGene00012762') # kind of hot region, highest point in "depleted"
data %<>% filter(!is.na(din.status.description))


# trim extreme .1%
q.L1.chipsig = quantile(data$L1.log_chip_signal_mean, c(1-.9995,.9995))
q.rlogc.L1 = quantile(data$rlogc.L1, c(1-.9995,.9995),na.rm=T)
data %<>% filter(between(L1.log_chip_signal_mean, q.L1.chipsig[1],q.L1.chipsig[2]))
data %<>% filter(between(rlogc.L1, q.rlogc.L1[1],q.rlogc.L1[2]))

# base model (0): chip signal
mod.L10 = lm.combo(rlogc.L1 ~ L1.log_chip_signal_mean, 
                       data = data)

mod.L10$label = "ChIP signal only"
mod.L11 = lm.combo(rlogc.L1 ~ L1.log_chip_signal_mean * L1_bound, 
                       data = data)
.mod.L11 = lm(rlogc.L1 ~ L1.log_chip_signal_mean * L1_bound, 
                       data = data)

L1_contrast_bound_unbound = contrast(.mod.L11, list(L1_bound=FALSE,
                    L1.log_chip_signal_mean=mean(data$L1.log_chip_signal_mean)),
         list(L1_bound=TRUE,
              L1.log_chip_signal_mean=mean(data$L1.log_chip_signal_mean))
         )

mod.L11$label = "ChIP signal AND ELT-2 binding"


mod.L12 = lm.combo(rlogc.L1 ~ L1.log_chip_signal_mean * L1_bound * din.status.description, 
                       data = data)
.mod.L12 = lm(rlogc.L1 ~ L1.log_chip_signal_mean * L1_bound * din.status.description, 
                       data = data)
contrast(.mod.L12, list(L1_bound=TRUE,
                       din.status.description="unchanged_ELT2_minus",
                       L1.log_chip_signal_mean=mean(data$L1.log_chip_signal_mean)),
         list(L1_bound=TRUE,
              din.status.description="up_ELT2_minus",
              L1.log_chip_signal_mean=mean(data$L1.log_chip_signal_mean))
         )
contrast(.mod.L12, list(L1_bound=FALSE,
                       din.status.description="unchanged_ELT2_minus",
                       L1.log_chip_signal_mean=mean(data$L1.log_chip_signal_mean)),
         list(L1_bound=TRUE,
              din.status.description="unchanged_ELT2_minus",
              L1.log_chip_signal_mean=mean(data$L1.log_chip_signal_mean))
         )

L1.straightup.cor = cor(data$L1.log_chip_signal_mean, data$rlogc.L1)
dbound = data %>% filter(L1_bound)
dunbound = data %>% filter(!L1_bound)
L1.bound.cor = cor.test(dbound$L1.log_chip_signal_mean, dbound$rlogc.L1, conf.level=.975)
L1.unbound.cor = cor.test(dunbound$L1.log_chip_signal_mean, dunbound$rlogc.L1, conf.level=.975)

data %<>% mutate(elt2.binding = factor(ifelse(L1_bound, "ELT-2 bound", "ELT-2 unbound"),
                                       levels = c("ELT-2 unbound","ELT-2 bound")))

p1=ggplot(data, 
       aes(x=L1.log_chip_signal_mean, 
           y=rlogc.L1, 
           #group=elt2.binding, 
           color=elt2.binding)) + 
  geom_point(alpha=.5) +
  geom_smooth(color="black", method="lm", formula = y~x, se=F) + 
  #stat_poly_eq(parse=T, aes(label = ..rr.label..), formula=y~x) +
  ggtitle(bquote(.(mod.L10$label) ~ R^2 == .(round(mod.L10$r.squared,3)))) +
  ylab("DESeq2 rlog counts") +
  xlab("L1 log ChIP promoter signal") +
  scale_color_manual(values=okabe) #+ 
  #guides(color="none")

p2=ggplot(data,
       aes(x= L1.log_chip_signal_mean, 
           y=rlogc.L1, 
           #group=elt2.binding, 
           color=elt2.binding
           )) + geom_point() +
  stat_smooth(color="black", method="lm", formula = y~x, se=F) + 
  stat_poly_eq(parse=T, aes(label = ..rr.label..), formula=y~x, color="black") +
  ylim(c(0,19)) + 
  #xlim(c(0,11)) +
  facet_wrap(~elt2.binding ) +
  ylab("DESeq2 rlog counts") + 
  xlab("L1 log ChIP promoter signal") +
  ggtitle("L1 Expression level (ELT-2 bound/unbound)") +
  scale_color_manual(values=okabe) + 
  guides(color="none") + theme_bw()

data.L1 = data
```

```{r L1-p3}
data = data.L1
p3=ggplot(data %>% filter(!is.na(din.status.description)),
       aes(x= L1.log_chip_signal_mean, 
           y=rlogc.L1, 
           #group=elt2.binding, 
           color=elt2.binding
           )) + geom_point() +
  stat_smooth(method="lm", formula = y~x, se=F, color="black", fullrange = T) + 
  stat_poly_eq(parse=T, 
               aes(label = paste(after_stat(..rr.label..), 
                                 after_stat(..n.label..), 
                                 sep="*\", \"*")), # https://www.rdocumentation.org/packages/ggpmisc/versions/0.4.5/topics/stat_poly_eq
          
               formula=y~x, 
               color="black",
               label.y=0) +
  geom_density_2d(colour="black", size=.1, alpha=1) +
  ylim(c(0,19)) + 
  #xlim(c(0,11)) +
  facet_wrap(~L1_bound + din.status.description ) +
  ylab("DESeq2 rlog counts") + 
  xlab("L1 log ChIP promoter signal") +
  ggtitle("L1 Expression level (ELT-2 bound/unbound)") +
  scale_color_manual(values=okabe) + 
  theme_bw() + 
  guides(color="none"); p3
ggsave("plots/signal_cor.xy.L1.dineen.status.pdf", height=5,width=12)
```

```{r violin}

t.test(rlogc.L1 ~ elt2.binding, data = data.L1 %>% filter(!is.na(din.status.description) & din.status.description == "down_ELT2_minus"), conf.level = 1-(.05/3) )

t.test(rlogc.L1 ~ elt2.binding, data = data.L1 %>% filter(!is.na(din.status.description) & din.status.description == "up_ELT2_minus"), conf.level = 1-(.05/3) )

t.test(rlogc.L1 ~ elt2.binding, data = data.L1 %>% filter(!is.na(din.status.description) & din.status.description == "unchanged_ELT2_minus"), conf.level = 1-(.05/3) )

ggviolin(data.L1 %>% filter(!is.na(din.status.description)),
     x= "elt2.binding", 
     y="rlogc.L1", 
     add = c("mean_ci"),
     add.params = list(size=.5,ci=1 - (.05/3)),
    color="elt2.binding",
    error.plot = "crossbar",
    fill=NA,
    palette = okabe,ggtheme=theme_bw(),
    facet.by = "din.status.description", 
    panel.labs=list(din.status.description=c("down ELT-2 minus",
                                             "unchanged ELT-2 minus",
                                             "up ELT-2 minus"))) + 
  ggtitle("Expression level as a function of whether a locus is bound by ELT-2") +
  xlab("") + ylab("Expression level (rlog counts)") +
  theme(axis.text.x = element_text(angle = 90)) +
  guides(color="none") 
ggsave("plots/signal_cor.violin.L1.dineen.status.pdf", height=5,width=12)
```


```{r L1-final-plot}
title <- ggdraw() + 
  draw_label(
    "L1: Intestine enriched and equal expressed genes predicted by ChIP signal level",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    # add margin on the left of the drawing canvas,
    # so title is aligned with left edge of first plot
    plot.margin = margin(0, 0, 0, 7)
  )
# plot_grid(title, p1, p2, p3, ncol=1,labels=c('','A','B','C'), rel_heights = c(0.1, 1, 1, 1));  ggsave("plots/signal_cor.xy.L1.pdf", height=15,width=12)

# middle one only (bound vs. unbound)
plot_grid(title, p2, ncol=1,rel_heights = c(0.1,1)); 
ggsave("plots/signal_cor.xy.L1.pdf", height=5,width=12)

L1.p.title = title
L1.p1 = p1


# based on the ANOVA, use a reduced model to isolate meaningful coefficients for meaningful contrasts
data$din.status.description = factor(data$din.status.description, c("unchanged_ELT2_minus", "down_ELT2_minus", "up_ELT2_minus"))
mod.reduced0 = lm.combo(rlogc.L1 ~ L1.log_chip_signal_mean * L1_bound * din.status.description, data = data)
mod.reduced = lm.combo(rlogc.L1 ~ L1.log_chip_signal_mean:L1_bound + din.status.description, data = data)
smack = lm.combo(rlogc.L1 ~ L1.log_chip_signal_mean + din.status.description, data = data)
smack2 = lm.combo(rlogc.L1 ~ L1.log_chip_signal_mean*L1_bound  + din.status.description, data = data)

```

## L3

```{r L3-r-squared}
data = alldata %>% filter(L3_int_exp %in% c('enriched'))
#data %<>% filter(WBGeneID != 'WBGene00016153') # negative signal, lowest point
#data %<>% filter(WBGeneID != 'WBGene00012762') # kind of hot region, highest point in "depleted"

# trim extreme .1%
q.L3.chipsig = quantile(data$L3.log_chip_signal_mean, c(1-.9995,.9995))
q.rlogc.L3 = quantile(data$rlogc.L3, c(1-.9995,.9995),na.rm=T)
data %<>% filter(between(L3.log_chip_signal_mean, q.L3.chipsig[1],q.L3.chipsig[2]))
data %<>% filter(between(rlogc.L3, q.rlogc.L3[1],q.rlogc.L3[2]))

# base model (0): chip signal
mod.L30 = lm.combo(rlogc.L3 ~ L3.log_chip_signal_mean, 
                       data = data)

mod.L30$label = "ChIP signal only"
mod.L31 = lm.combo(rlogc.L3 ~ L3.log_chip_signal_mean * L3_bound, 
                       data = data)
.mod.L31 = lm(rlogc.L3 ~ L3.log_chip_signal_mean * L3_bound, 
                       data = data)

L3_contrast_bound_unbound = contrast(.mod.L31, list(L3_bound=FALSE,
                    L3.log_chip_signal_mean=mean(data$L3.log_chip_signal_mean)),
         list(L3_bound=TRUE,
              L3.log_chip_signal_mean=mean(data$L3.log_chip_signal_mean))
         )

mod.L31$label = "ChIP signal AND ELT-2 binding"

L3.straightup.cor = cor(data$L3.log_chip_signal_mean, data$rlogc.L3)
dbound = data %>% filter(L3_bound)
dunbound = data %>% filter(!L3_bound)
L3.bound.cor = cor.test(dbound$L3.log_chip_signal_mean, dbound$rlogc.L3, conf.level=.975)
L3.unbound.cor = cor.test(dunbound$L3.log_chip_signal_mean, dunbound$rlogc.L3, conf.level=.975)

data %<>% mutate(elt2.binding = factor(ifelse(L3_bound, "ELT-2 bound", "ELT-2 unbound"),
                                       levels = c("ELT-2 unbound","ELT-2 bound")))

p1=ggplot(data, 
       aes(x=L3.log_chip_signal_mean, 
           y=rlogc.L3, 
           #group=elt2.binding, 
           color=elt2.binding)) + 
  geom_point(alpha=.5) +
  geom_smooth(color="black", method="lm", formula = y~x, se=F) + 
  #stat_poly_eq(parse=T, aes(label = ..rr.label..), formula=y~x) +
  #ggtitle(bquote(.(mod.L30$label) ~ R^2 == .(round(mod.L30$r.squared,3)))) +
  ylab("DESeq2 rlog counts") +
  xlab("L3 log ChIP promoter signal") +
  scale_color_manual(values=okabe) #+ 
  #guides(color="none")
p1

p2=ggplot(data,
       aes(x= L3.log_chip_signal_mean, 
           y=rlogc.L3, 
           #group=elt2.binding, 
           color=elt2.binding
           )) + geom_point() +
  stat_smooth(color="black", method="lm", formula = y~x, se=F) + 
  stat_poly_eq(parse=T, aes(label = ..rr.label..), formula=y~x, color="black") +
  ylim(c(0,19)) + 
  #xlim(c(0,11)) +
  facet_wrap(~elt2.binding ) +
  ylab("DESeq2 rlog counts") + 
  xlab("L3 log ChIP promoter signal") +
  ggtitle("L3 Expression level (ELT-2 bound/unbound)") +
  scale_color_manual(values=okabe) + 
  guides(color="none") + theme_bw()

p3=ggplot(data %>% filter(!is.na(din.status.description)),
       aes(x= L3.log_chip_signal_mean, 
           y=rlogc.L3, 
           #group=elt2.binding, 
           color=elt2.binding
           )) + geom_point() +
  stat_smooth(method="lm", formula = y~x, se=F) + 
  stat_poly_eq(parse=T, aes(label = ..rr.label..), formula=y~x) +
  ylim(c(0,19)) + 
  #xlim(c(0,11)) +
  facet_wrap(~din.status.description ) +
  ylab("DESeq2 rlog counts") + 
  xlab("L3 log ChIP promoter signal") +
  ggtitle("L3 Expression level (ELT-2 bound/unbound)") +
  scale_color_manual(values=okabe) + 
  guides(color="none"); p3


title <- ggdraw() + 
  draw_label(
    "L3: Intestine enriched and equal expressed genes predicted by ChIP signal level",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    # add margin on the left of the drawing canvas,
    # so title is aligned with left edge of first plot
    plot.margin = margin(0, 0, 0, 7)
  )
# plot_grid(title, p1, p2, p3, ncol=1,labels=c('','A','B','C'), rel_heights = c(0.1, 1, 1, 1));  ggsave("plots/signal_cor.xy.L3.pdf", height=15,width=12)

# middle one only (bound vs. unbound)
plot_grid(title, p2, ncol=1,rel_heights = c(0.1,1)); 
ggsave("plots/signal_cor.xy.L3.pdf", height=5,width=12)

L3.p.title = title
L3.p1 = p1
```

```{r all-plots}
title <- ggdraw() + 
  draw_label(
    "Expression level of Intestine enriched and equal expressed genes predicted by ChIP signal intensity",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    # add margin on the left of the drawing canvas,
    # so title is aligned with left edge of first plot
    plot.margin = margin(0, 0, 0, 7)
  )

plot_grid(title, 
          LE.p1 + ggtitle(bquote("Embryo " ~ R^2 == .(round(mod.embryo0$r.squared,3)))),
          L1.p1 + ggtitle(bquote("L1 " ~ R^2 == .(round(mod.L10$r.squared,3)))),
          L3.p1 + ggtitle(bquote("L3 " ~ R^2 == .(round(mod.L30$r.squared,3)))),
          ncol=1,labels=c('','A','B','C'), rel_heights = c(0.1, 1, 1, 1))
ggsave("plots/signal_cor.xy.final.pdf", height=15,width=12)
```

```{r kabels-regression-stats}

kable(mod.embryo1$coefficients, digits=4)
kable(mod.L11$coefficients, digits=4)
kable(mod.L12$anova, digits=4)
kable(mod.L31$coefficients, digits=4)

write.table(mod.embryo1$coefficients, file="../03_output/correlation_regression.stats.embryo.txt", sep="\t", quote=F)
write.table(mod.embryo1$anova, file="../03_output/correlation_regression.anova.embryo.txt", sep="\t", quote=F)
write.table(mod.L11$coefficients, file="../03_output/correlation_regression.stats.L1.txt", sep="\t", quote=F)
write.table(mod.L12$anova, file="../03_output/correlation_regression.anova.dineen.L1.txt", sep="\t", quote=F)
write.table(mod.L31$coefficients, file="../03_output/correlation_regression.stats.L3.txt", sep="\t", quote=F)
write.table(mod.L31$anova, file="../03_output/correlation_regression.anova.L3.txt", sep="\t", quote=F)

# use "contrast" to test bound vs not (lm coefficients only test the intercept and slope terms individually)

cat(capture.output(embryo_contrast_bound_unbound), file="../03_output/correlation_regression.contrast_bound_unbound.embryo.txt", sep="\t")

cat(capture.output(L1_contrast_bound_unbound), file="../03_output/correlation_regression.contrast_bound_unbound.L1.txt", sep="\t")

cat(capture.output(L3_contrast_bound_unbound), file="../03_output/correlation_regression.contrast_bound_unbound.L3.txt", sep="\t")

```

# Use stage in model

```{r stage-as-variable}

data = alldata %>% filter(embryo_int_exp == "enriched") %>% 
  select(LE.log_chip_signal_mean, LE_bound, rlogc.embryo) %>%
  dplyr::rename(log_chip_signal_mean=LE.log_chip_signal_mean,
                rlogc = rlogc.embryo,
                ELT2bound = LE_bound) %>%
  mutate(stage = "embryo")
data = alldata %>% filter(L1_int_exp == "enriched") %>% 
  select(L1.log_chip_signal_mean, L1_bound, rlogc.L1) %>%
  dplyr::rename(log_chip_signal_mean=L1.log_chip_signal_mean,
                rlogc = rlogc.L1,
                ELT2bound = L1_bound) %>%
        mutate(stage = "L1")  %>%
        rbind(data)
                                                                                    
data = alldata %>% filter(L3_int_exp == "enriched") %>% 
  select(L3.log_chip_signal_mean, L3_bound, rlogc.L3) %>%
  dplyr::rename(log_chip_signal_mean=L3.log_chip_signal_mean,
                rlogc = rlogc.L3,
                ELT2bound = L3_bound) %>%
        mutate(stage = "L3")  %>%
        rbind(data)

data$stage = factor(data$stage, levels=c("L1", "embryo","L3"))
mod.log_chip_mean = lm.combo(rlogc ~ log_chip_signal_mean, data=data)
mod.log_chip_mean = lm.combo(rlogc ~ log_chip_signal_mean, data=data)
mod.all = lm.combo(rlogc ~ log_chip_signal_mean * stage * ELT2bound, data=data)
mod.notStage = lm.combo(rlogc ~ log_chip_signal_mean * ELT2bound, data=data)
mod.notELT2bound = lm.combo(rlogc ~ log_chip_signal_mean * stage, data=data)
# FWER
fwer = cbind(mod.all$coefficients[,c(1,4)], 
             p.adjust(mod.all$coefficients[,4],method = "holm"),
             p.adjust(mod.all$coefficients[,4],method = "bonferroni"))
colnames(fwer) <- c("Estimate", "Pr(>|t|)", "FWER (holm)", "FWER (bonferroni)")
```

```{r plot-all-combined}
p2=ggplot(data %>% mutate(stage=forcats::fct_relevel(stage, c("embryo","L1","L3"))),
       aes(x= log_chip_signal_mean, 
           y=rlogc, 
           group=ELT2bound,
           color=ELT2bound
           )) + geom_point() +
  stat_smooth(color="black", method="lm", formula = y~x, se=F, fullrange = T) + 
  stat_poly_eq(parse=T, 
               aes(label = paste(after_stat(..rr.label..), 
                                 after_stat(..n.label..), 
                                 sep="*\", \"*")), # https://www.rdocumentation.org/packages/ggpmisc/versions/0.4.5/topics/stat_poly_eq
               formula=y~x, 
               color="black",
               label.y=0) +
  geom_density_2d(colour="black", size=.1, alpha=1) +
  ylim(c(0,19)) + 
  #xlim(c(0,11)) +
  facet_wrap(~ELT2bound + stage ) +
  #facet_wrap(~stage ) +
  ylab("DESeq2 rlog counts") + 
  xlab("All log ChIP promoter signal") +
  ggtitle("All Expression level (ELT-2 bound/unbound)") +
  scale_color_manual(values=okabe) +  geom_density_2d(colour="black", size=.1, alpha=1) +
  guides(color="none") + theme_bw()
p2
                                                                                                    
```

```{r contrasts-all-model}

.mod.all = lm(rlogc ~ log_chip_signal_mean * stage * ELT2bound, data=data)
ols.mod = ols(rlogc ~ log_chip_signal_mean * stage * ELT2bound, data=data)

chip_sigs = data %>%filter(stage=="embryo") %>% pull(log_chip_signal_mean) %>% range()

contrast_embryo_binding=contrast(ols.mod, list(ELT2bound=FALSE,
                    log_chip_signal_mean=chip_sigs,
                    stage = "embryo"),
                  list(ELT2bound=TRUE,
                    log_chip_signal_mean=chip_sigs,
                    stage="embryo"), conf.int = 1-(.05/3))
df_contrast_embryo_binding = contrast_embryo_binding[c("log_chip_signal_mean", "stage", "Contrast","Lower","Upper")] %>% as.data.frame()



chip_sigs = data %>%filter(stage=="L1") %>% pull(log_chip_signal_mean) %>% range()
contrast_L1_binding=contrast(ols.mod, list(ELT2bound=FALSE,
                    log_chip_signal_mean=chip_sigs,
                    stage = "L1"),
                  list(ELT2bound=TRUE,
                    log_chip_signal_mean=chip_sigs,
                    stage="L1"), conf.int = 1-(.05/3))
df_contrast_L1_binding = contrast_L1_binding[c("log_chip_signal_mean", "stage",  "Contrast","Lower","Upper")] %>% as.data.frame()




chip_sigs = data %>%filter(stage=="L3") %>% pull(log_chip_signal_mean) %>% range()
contrast_L3_binding = contrast(ols.mod, list(ELT2bound=FALSE,
                    log_chip_signal_mean=chip_sigs,
                    stage = "L3"),
                  list(ELT2bound=TRUE,
                    log_chip_signal_mean=chip_sigs,
                    stage="L3"), conf.int = 1-(.05/3))
df_contrast_L3_binding = contrast_L3_binding[c("log_chip_signal_mean","stage", "Contrast","Lower","Upper")] %>% as.data.frame()

df_binding_contrasts = rbind(
  df_contrast_embryo_binding,
  df_contrast_L1_binding,
  df_contrast_L3_binding
)

ggplot(df_binding_contrasts, aes(x=log_chip_signal_mean, y=Contrast)) + geom_line() + 
   geom_ribbon(aes(ymin=Lower, ymax=Upper), width=0, alpha=0.15, linetype=0) +
  facet_wrap(~stage) + theme_bw()


chip_sigs = data %>% filter(stage %in% c("L1","L3")) %>% pull(log_chip_signal_mean) %>% range()
contrast_embryo_L1 = contrast(ols.mod, list(ELT2bound=TRUE,
                    log_chip_signal_mean=chip_sigs,
                    stage = c("embryo")),
         list(ELT2bound=TRUE,
                    log_chip_signal_mean=chip_sigs,
                    stage = c( "L1")))
df_contrast_embryo_L1 = contrast_embryo_L1[c("log_chip_signal_mean","Contrast","Lower","Upper")] %>% as.data.frame()

chip_sigs = data %>% filter(stage %in% c("L1","L3")) %>% pull(log_chip_signal_mean) %>% range()
contrast_L1_L3 = contrast(ols.mod, list(ELT2bound=TRUE,
                    log_chip_signal_mean=chip_sigs,
                    stage = c("L1")),
         list(ELT2bound=TRUE,
                    log_chip_signal_mean=chip_sigs,
                    stage = c( "L3")));#contrast_L1_L3
df_c_L1_L3 = contrast_L1_L3[c("log_chip_signal_mean","Contrast","Lower","Upper")] %>% as.data.frame()

ggplot(df_c_L1_L3, aes(x=log_chip_signal_mean, y=Contrast)) + geom_line() + 
   geom_ribbon(aes(ymin=Lower, ymax=Upper), width=0, alpha=0.15, linetype=0)
```

```{r construct-data-rsquare-check}

d.X = seq(8,10,length.out=150)
d.Y = 1.1 * d.X + rnorm(length(d.X))
df = data.frame(d.X,d.Y,slope=1.1,sd=1)

d.X = seq(8,10,length.out=150)
d.Y = 1.1 * d.X + rnorm(length(d.X), 0, 2)
df = rbind(df, data.frame(d.X,d.Y,slope=1.1,sd=2))


d.X = seq(8,10,length.out=150)
d.Y = 1.01 * d.X + rnorm(length(d.X))
df = rbind(df, data.frame(d.X,d.Y,slope=1.01,sd=1))

d.X = seq(8,10,length.out=150)
d.Y = 1.01 * d.X + rnorm(length(d.X), 0, 2)
df = rbind(df, data.frame(d.X,d.Y,slope=1.01,sd=2))

df$sd = factor(df$sd)
df$slope = factor(df$slope)
ggplot(df, aes(x=d.X,y=d.Y, color=slope)) + geom_point() + 
  stat_smooth(color="black", method="lm", formula = y~x, se=F, fullrange = T) +
  stat_poly_eq(parse=T, 
               aes(label = paste(after_stat(..rr.label..), 
                                 after_stat(..n.label..), 
                                 sep="*\", \"*")), # https://www.rdocumentation.org/packages/ggpmisc/versions/0.4.5/topics/stat_poly_eq
               formula=y~x, 
               color="black",
               label.y=0) +
  geom_density_2d(colour="black", size=.1, alpha=1) + 
  ylim(c(0,19)) + 
  facet_wrap(~sd + slope) + 
  xlim(c(5,14)) + 
  scale_color_manual(values=okabe) +
  guides(color="none") + theme_bw()
```
